stages:
  - setup
  - build
  - cleanup

# Base image setup
image: ros:humble

variables:
  ROS_DISTRO: humble
  DEBIAN_FRONTEND: noninteractive

# Job to set up dependencies
setup_dependencies:
  stage: setup
  script:
    - apt-get update
    - apt-get install -y \
      git \
      build-essential \
      libglfw3-dev \
      libx11-dev \
      xorg-dev \
      ros-humble-urdf \
      ros-humble-xacro \
      ros-humble-rviz2 \
      ros-humble-ros2-control \
      ros-humble-ros2-controllers \
      ros-humble-controller-manager \
      libopencv-dev \
      ros-humble-pcl-conversions \
      ros-humble-cv-bridge \
      libpcl-dev
    - rosdep init
    - rosdep update

# Job to clone and build MuJoCo
build_mujoco:
  stage: build
  script:
    - mkdir /git
    - cd /git
    - git clone https://github.com/deepmind/mujoco
    - cd mujoco
    - cmake .
    - cmake --build .
    - cmake --install .
  cache:
    key: mujoco_build_cache
    paths:
      - /git/mujoco/build

# Job to build ROS 2 workspace
build_ros2_workspace:
  stage: build
  script:
    - mkdir -p /ros2_ws/src
    - cp -r $CI_PROJECT_DIR/mujoco_ros2_control /ros2_ws/src/
    - cd /ros2_ws
    - . /opt/ros/$ROS_DISTRO/setup.sh
    - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
    - colcon build
  artifacts:
    paths:
      - /ros2_ws/install
    expire_in: 1 week

# Job to clean up build artifacts (optional)
cleanup:
  stage: cleanup
  script:
    - rm -rf /git
    - echo "Cleanup completed."