stages:          # List of stages for jobs, and their order of execution
  - build
  #- test
  #- deploy

build_job:
  stage: build
  image: docker:20.10.7 # Use the official Docker image to build other Docker images
  services:
    - docker:20.10.7-dind # Docker-in-Docker service for building Docker images
  script:
    # Build the Docker image with the desired Dockerfile content
    - docker build -t mujoco_ros2_control:latest .
  
  # Cache for dependencies (optional)
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - $WORKDIR/.colcon_cache
  
  # Artifacts (optional, you can save the Docker image or other files for later stages)
  artifacts:
    paths:
      - $WORKDIR/install
    expire_in: 1 week
