"""Launch the Unitree G1 (29-DOF) MuJoCo example.

The robot holds its default (start) pose using the PD gains baked into the
ros2_control block - the MujocoSystem hardware turns a position setpoint into
torque itself. On top of the state/sensor broadcasters, one
JointGroupPositionController per limb (plus the waist) forwards those setpoints,
so the pose can be commanded over /<group>_position_controller/commands. The
model also carries a depth camera (/d435/...) and a LiDAR (/lidar_head/...).

`low_level:=true` drives it the way the real robot is driven instead: the
UnitreeHgLowLevel plugin closes the motor PD loop inside the simulation, taking
unitree_hg/LowCmd on /lowcmd and publishing unitree_hg/LowState on /lowstate at
500 Hz, so a G1 policy can talk to MuJoCo unchanged. The joints then export state
only, the position controllers are not started, and the broadcasters carry on as
before. The plugin itself never invents a command, so the start pose in
config/unitree_g1/hold_start_message.yaml is published on /lowcmd at 50 Hz
alongside it -- the robot stands there waiting instead of collapsing, and stands
back up after a /mujoco_reset. A policy publishes faster than 50 Hz and so wins
the topic; stop the publisher (or launch with `hold_pose:=false`) to be rid of it
altogether.

The robot spawns on a Voronoi stepping-stones field generated by
mujoco_ros2_control's prepare_terrain.py - stones of varying height with tilted
tops, separated by gaps. Pass `terrain:=flat` for plain ground instead. Either
way the spawn point is a flat platform whose top is at z=0, so the spawn height
below does not change with the terrain.
"""

import os

from ament_index_python import get_package_share_directory

from launch import LaunchDescription, LaunchContext
from launch.actions import (
    DeclareLaunchArgument,
    ExecuteProcess,
    LogInfo,
    RegisterEventHandler,
    OpaqueFunction,
)
from launch.event_handlers import OnProcessStart, OnProcessExit
from launch_ros.actions import Node
from launch.substitutions import LaunchConfiguration
from launch.conditions import IfCondition

import xacro


def create_nodes(context: LaunchContext):
    namespace = ""
    mujoco_model_path = "/tmp/mujoco"
    mujoco_model_file = os.path.join(mujoco_model_path, "main.xml")

    rviz = LaunchConfiguration("rviz")
    # The description and the controller list both change with it, so it is read
    # here rather than used as a condition on the spawners.
    low_level = LaunchConfiguration("low_level").perform(context).lower() in (
        "true", "1", "yes"
    )

    unitree_g1_xacro_filepath = os.path.join(
        get_package_share_directory("mujoco_ros2_control_examples"),
        "urdf",
        "unitree_g1",
        "unitree_g1.urdf.xacro",
    )

    robot_description = {
        "robot_description": xacro.process_file(
            unitree_g1_xacro_filepath,
            mappings={
                "name": "unitree_g1",
                "mujoco": "true",
                "low_level": "true" if low_level else "false",
            },
        ).toprettyxml(indent="  ")
    }

    # The terrain is generated outside mujoco_model_path on purpose: xacro2mjcf
    # wipes that directory on startup, before it reads any of its input files.
    terrain_dir = "/tmp/mujoco_terrain"
    terrain = LaunchConfiguration("terrain").perform(context)

    if terrain == "stones":
        scene_file = os.path.join(terrain_dir, "terrain_scene.xml")
        prepare_terrain = Node(
            package="mujoco_ros2_control",
            executable="prepare_terrain_node.py",
            parameters=[{
                "out_dir": terrain_dir,
                "difficulty": float(LaunchConfiguration("terrain_difficulty").perform(context)),
                "seed": int(LaunchConfiguration("terrain_seed").perform(context)),
                "collider": LaunchConfiguration("terrain_collider").perform(context),
                "field_half": float(LaunchConfiguration("terrain_field_half").perform(context)),
                "max_height_var": float(
                    LaunchConfiguration("terrain_height_var").perform(context)),
                "max_tilt_deg": float(LaunchConfiguration("terrain_tilt_deg").perform(context)),
                "max_drop_frac": float(LaunchConfiguration("terrain_hole_frac").perform(context)),
            }],
            output="screen",
        )
    else:
        scene_file = os.path.join(
            get_package_share_directory("mujoco_ros2_control"), "mjcf", "scene.xml"
        )
        prepare_terrain = None

    xacro2mjcf = Node(
        package="mujoco_ros2_control",
        executable="xacro2mjcf.py",
        parameters=[
            {"robot_descriptions": [robot_description["robot_description"]]},
            {"input_files": [scene_file]},
            {"output_file": mujoco_model_file},
            {"mujoco_files_path": mujoco_model_path},
            {"base_link": "pelvis"},
            {"floating": True},
            {"initial_position": "0 0 0.78"},
            {"initial_orientation": "0 0 0"},
        ],
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        namespace=namespace,
        parameters=[robot_description, {"use_sim_time": True}],
    )

    ros2_control_params_file = os.path.join(
        get_package_share_directory("mujoco_ros2_control_examples"),
        "config",
        "unitree_g1",
        "unitree_g1_controllers.yaml",
    )

    mujoco = Node(
        package="mujoco_ros2_control",
        executable="mujoco_ros2_control",
        namespace=namespace,
        output="screen",
        parameters=[
            robot_description,
            ros2_control_params_file,
            {"simulation_frequency": 1000.0},
            {"realtime_factor": 1.0},
            {"robot_model_path": mujoco_model_file},
            {"show_gui": True},
        ],
        remappings=[
            ("/controller_manager/robot_description", "/robot_description"),
        ],
    )

    # Nothing may read the scene before it exists, so xacro2mjcf waits for the
    # generator when there is one and starts straight away when there is not.
    if prepare_terrain is not None:
        first_action = prepare_terrain
        start_conversion = [
            RegisterEventHandler(
                OnProcessExit(
                    target_action=prepare_terrain,
                    on_exit=[
                        LogInfo(msg="Generated stepping-stones terrain, "
                                    "converting the model..."),
                        xacro2mjcf,
                    ],
                )
            )
        ]
    else:
        first_action = xacro2mjcf
        start_conversion = []

    start_mujoco = RegisterEventHandler(
        OnProcessExit(
            target_action=xacro2mjcf,
            on_exit=[
                LogInfo(msg="Created mujoco xml, starting mujoco node..."),
                mujoco,
            ],
        )
    )

    joint_state_broadcaster = Node(
        package="controller_manager",
        executable="spawner",
        arguments=[
            "joint_state_broadcaster",
            "--controller-manager", ["/", "controller_manager"],
        ],
    )
    pelvis_imu_broadcaster = Node(
        package="controller_manager",
        executable="spawner",
        arguments=[
            "pelvis_imu_broadcaster",
            "--controller-manager", ["/", "controller_manager"],
            "--param-file", ros2_control_params_file,
        ],
    )
    pelvis_pose_broadcaster = Node(
        package="controller_manager",
        executable="spawner",
        arguments=[
            "pelvis_pose_broadcaster",
            "--controller-manager", ["/", "controller_manager"],
            "--param-file", ros2_control_params_file,
        ],
    )

    # The PD hold lives in the hardware, so these only forward position
    # setpoints to it - starting them changes nothing until a command arrives.
    # With low_level:=true there is nothing for them to claim: the joints export
    # no command interfaces, and the plugin drives them over /lowcmd instead.
    position_controllers = [] if low_level else [
        Node(
            package="controller_manager",
            executable="spawner",
            arguments=[
                f"{group}_position_controller",
                "--controller-manager", ["/", "controller_manager"],
                "--param-file", ros2_control_params_file,
            ],
        )
        for group in ("left_leg", "right_leg", "waist", "left_arm", "right_arm")
    ]

    g1_hold_start_message = os.path.join(
        get_package_share_directory("mujoco_ros2_control_examples"),
        "config",
        "unitree_g1",
        "hold_start_message.yaml",
    )

    # `ros2 topic pub` takes the message as a literal argument, not a file path,
    # so something has to read the file - but not this launch description: launch
    # logs an ExecuteProcess action's `cmd` verbatim whenever the process exits
    # non-zero, which a SIGINT (how this one is normally stopped) does, and the
    # whole YAML would land in the terminal on every shutdown. `cat` reads it in
    # the shell instead, so the `cmd` this action stores - and that gets logged -
    # is just this fixed string and a path.
    hold_pose = [
        ExecuteProcess(
            cmd=[
                "bash", "-c",
                'exec ros2 topic pub --rate 50 /lowcmd unitree_hg/msg/LowCmd '
                '"$(cat "$1")"',
                "_", g1_hold_start_message,
            ],
            output="log",
            condition=IfCondition(LaunchConfiguration("hold_pose")),
        )
    ] if low_level else []

    rviz_config_file = os.path.join(
        get_package_share_directory("mujoco_ros2_control_examples"),
        "config",
        "unitree_g1",
        "default.rviz",
    )

    rviz_node = Node(
        condition=IfCondition(rviz),
        package="rviz2",
        executable="rviz2",
        name="rviz2",
        output="log",
        arguments=["-d", rviz_config_file],
        parameters=[{"use_sim_time": True}],
    )

    load_controllers = RegisterEventHandler(
        OnProcessStart(
            target_action=mujoco,
            on_start=[
                LogInfo(msg="Starting broadcasters and controllers..."),
                joint_state_broadcaster,
                pelvis_imu_broadcaster,
                pelvis_pose_broadcaster,
                *position_controllers,
                rviz_node,
            ],
        )
    )

    return [
        robot_state_publisher,
        *hold_pose,
        first_action,
        *start_conversion,
        start_mujoco,
        load_controllers,
    ]


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument(
            "rviz",
            default_value="true",
            description="Start rviz.",
        ),
        DeclareLaunchArgument(
            "low_level",
            default_value="false",
            choices=["true", "false"],
            description="Drive the joints over unitree_hg/LowCmd through the "
                        "UnitreeHgLowLevel plugin, as on the real G1, instead of "
                        "through the ros2_control position controllers.",
        ),
        DeclareLaunchArgument(
            "hold_pose",
            default_value="true",
            choices=["true", "false"],
            description="With low_level:=true, publish the start pose on /lowcmd "
                        "at 50 Hz so the robot stands while nothing else commands "
                        "it. Turn it off to drive /lowcmd entirely yourself.",
        ),
        DeclareLaunchArgument(
            "terrain",
            default_value="stones",
            choices=["flat", "stones"],
            description="Ground to spawn on: a Voronoi stepping-stones field, "
                        "or a flat plane.",
        ),
        DeclareLaunchArgument(
            "terrain_difficulty",
            default_value="0.5",
            description="Stepping-stones difficulty, 0 (large, close, level "
                        "stones) to 1 (small, far apart, uneven). Ignored when "
                        "terrain:=flat.",
        ),
        DeclareLaunchArgument(
            "terrain_seed",
            default_value="42",
            description="Stepping-stones RNG seed; the same seed always yields "
                        "the same field.",
        ),
        DeclareLaunchArgument(
            "terrain_collider",
            default_value="mesh",
            choices=["mesh", "hfield"],
            description="One convex prism per stone (crisp vertical walls), or a "
                        "single heightfield geom (walls sloped over one cell).",
        ),
        DeclareLaunchArgument(
            "terrain_field_half",
            default_value="15.0",
            description="Half-extent of the square stepping-stones field, m.",
        ),
        DeclareLaunchArgument(
            "terrain_height_var",
            default_value="0.10",
            description="How far stone tops sit above or below z=0 at "
                        "difficulty 1, m. 0 puts every stone at one level.",
        ),
        DeclareLaunchArgument(
            "terrain_tilt_deg",
            default_value="8.0",
            description="How far stone tops tilt out of horizontal at "
                        "difficulty 1, degrees. 0 keeps every top level.",
        ),
        DeclareLaunchArgument(
            "terrain_hole_frac",
            default_value="0.15",
            description="Fraction of stones dropped at difficulty 1, leaving "
                        "holes scattered through the field. 0 = no holes.",
        ),
        OpaqueFunction(function=create_nodes),
    ])
