import os

from ament_index_python import get_package_share_directory

from launch import LaunchDescription
import launch_ros
from launch_ros.descriptions import ComposableNode
from launch.actions import ExecuteProcess, RegisterEventHandler, LogInfo
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch.event_handlers import (OnExecutionComplete, OnProcessExit,
                                   OnProcessIO, OnProcessStart, OnShutdown)
from moveit_configs_utils import MoveItConfigsBuilder

import xacro
import yaml


def load_file(package_name, file_path):
    package_path = get_package_share_directory(package_name)
    absolute_file_path = os.path.join(package_path, file_path)

    try:
        with open(absolute_file_path, "r") as file:
            return file.read()
    except EnvironmentError:  # parent of IOError, OSError *and* WindowsError where available
        return None


def load_yaml(package_name, file_path):
    package_path = get_package_share_directory(package_name)
    absolute_file_path = os.path.join(package_path, file_path)

    try:
        with open(absolute_file_path, "r") as file:
            return yaml.safe_load(file)
    except EnvironmentError:  # parent of IOError, OSError *and* WindowsError where available
        return None


def generate_launch_description():
    namespace = ''
    command_interface = 'effort'

    robot_description_path = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'panda.urdf.xacro')

    robot_description_string = xacro.process_file(robot_description_path, mappings={
        'ros2_control_command_interface': command_interface,
        'name': 'panda',
        'origin_xyz': '0.5 0 0.875',
        'origin_rpy': '0 0 0',
        'world_name': 'base_link',
        'generate_world_frame': 'false',
        'ros2_control_plugin': 'mujoco_ros2_control/MujocoSystem'
    }).toxml()

    robot_description = {'robot_description': robot_description_string}

    mujoco_model_path = "/tmp/mujoco"
    mujoco_model_file = mujoco_model_path + "/panda.xml"

    mujoco_scene_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'mjcf',
        'panda_scene.xml')

    # Add a free joint
    mujoco_box_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'box.urdf')

    mujoco_table_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'table.urdf')

    xacro2mjcf = Node(
        package="mujoco_ros2_control",
        executable="xacro2mjcf.py",
        parameters=[{'robot_descriptions': [robot_description_string]},
                    # robot descriptions of ros robots (it is possible to load multiple robot descriptions, but ros use only one at time
                    {'input_files': [  # Paths to all files that must be included, like free joints or scene files
                        mujoco_scene_file,
                        mujoco_box_file,
                        #mujoco_table_file
                    ]},
                    {'output_file': mujoco_model_file},  # Path to the output file
                    {'mujoco_files_path': mujoco_model_path}]
        # Path to the output folder (the output file must be in this folder)
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        namespace=namespace,
        parameters=[robot_description]
    )

    ros2_control_params_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'config',
        'controllers.yaml'
    )

    mujoco = Node(
        package="mujoco_ros2_control",
        executable="mujoco_ros2_control",
        namespace=namespace,
        respawn=True,
        parameters=[
            robot_description,
            ros2_control_params_file,
            {"simulation_frequency": 1000.0},  # Hz
            {"realtime_factor": 1.0},  # 1.0 is realtime
            {"robot_model_path": mujoco_model_file},  # Path to the mujoco model file, that was generated by xacro2mjcf
            {"show_gui": True},  # Enable or disable the mujoco GUI
            {"clock_publisher_frequency": 0.0}]
        # If 0 the clock is published with sumulation frequency, otherwise it is in Hz
    )

    start_mujoco = RegisterEventHandler(
        OnExecutionComplete(
            target_action=xacro2mjcf,
            on_completion=[
                LogInfo(msg='Created mujoco xml'),
                mujoco
            ]
        )
    )

    load_joint_state_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'joint_state_broadcaster'],
        output='screen'
    )

    load_arm_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'cartesian_impedance_controller'],
        output='screen'
    )

    load_gripper_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'gripper_controller'],
        output='screen'
    )

    moveit_config = MoveItConfigsBuilder("panda", package_name="panda_moveit").to_moveit_configs()

    # Get parameters for the Servo node
    servo_params = {"moveit_servo": load_yaml('panda_moveit', 'config/servo.yml')}

    # Launch as much as possible in components
    container = launch_ros.actions.ComposableNodeContainer(
        name="moveit_servo_demo_container",
        namespace="/",
        package="rclcpp_components",
        executable="component_container_mt",
        composable_node_descriptions=[
            # Example of launching Servo as a node component
            # Assuming ROS2 intraprocess communications works well, this is a more efficient way.
            # ComposableNode(
            #     package="moveit_servo",
            #     plugin="moveit_servo::ServoServer",
            #     name="servo_server",
            #     parameters=[
            #         servo_params,
            #         moveit_config.robot_description,
            #         moveit_config.robot_description_semantic,
            #     ],
            # ),
            # launch_ros.descriptions.ComposableNode(
            #     package="robot_state_publisher",
            #     plugin="robot_state_publisher::RobotStatePublisher",
            #     name="robot_state_publisher",
            #     parameters=[moveit_config.robot_description],
            # ),
            # launch_ros.descriptions.ComposableNode(
            #     package="tf2_ros",
            #     plugin="tf2_ros::StaticTransformBroadcasterNode",
            #     name="static_tf2_broadcaster",
            #     parameters=[{"child_frame_id": "/kuka_lbr_base", "frame_id": "/world"}],
            # ),
            launch_ros.descriptions.ComposableNode(
                package="kuka_lbr_moveit2",
                plugin="kuka_lbr_moveit2::JoyToServoPub",
                name="controller_to_servo_node",
            ),
            launch_ros.descriptions.ComposableNode(
                package="joy",
                plugin="joy::Joy",
                name="joy_node",
            ),
        ],
        output="screen",
    )
    # Launch a standalone Servo node.
    # As opposed to a node component, this may be necessary (for example) if Servo is running on a different PC
    servo_node = launch_ros.actions.Node(
        package="moveit_servo",
        executable="servo_node_main",
        parameters=[
            servo_params,
            moveit_config.robot_description,
            moveit_config.robot_description_semantic,
            moveit_config.robot_description_kinematics,
        ],
        output="screen",
    )

    register_controllers = RegisterEventHandler(
        OnProcessStart(
            target_action=mujoco,
            on_start=[
                LogInfo(msg='MuJoCo started, spawning robot'),
                load_joint_state_controller,
                load_arm_controller,
                load_gripper_controller,
                container,
                servo_node
            ]
        )
    )

    return LaunchDescription(
        [
            start_mujoco,
            register_controllers,
            xacro2mjcf,
            robot_state_publisher,
        ]
    )
