import os

from ament_index_python import get_package_share_directory

from launch import LaunchDescription
import launch_ros
from launch.actions import ExecuteProcess, RegisterEventHandler, LogInfo
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch.event_handlers import (OnExecutionComplete, OnProcessExit,
                                   OnProcessIO, OnProcessStart, OnShutdown)

import xacro


def generate_launch_description():
    namespace = ''
    command_interface = 'effort'

    robot_description_path = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'panda.urdf.xacro')

    robot_description_string = xacro.process_file(robot_description_path, mappings={
        'ros2_control_command_interface': command_interface,
        'name': 'panda',
        'origin_xyz': '0 0 0.875',
        'origin_rpy': '0 0 0',
        'world_name': 'base_link',
        'generate_world_frame': 'false',
        'ros2_control_plugin': 'mujoco_ros2_control/MujocoSystem'
    }).toxml()

    robot_description = {'robot_description': robot_description_string}

    mujoco_model_path = "/tmp/mujoco"
    mujoco_model_file = mujoco_model_path + "/panda.xml"

    mujoco_scene_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'mjcf',
        'panda_scene.xml')

    # Add a free joint
    mujoco_box_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'box.urdf')

    mujoco_table_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'urdf',
        'table.urdf')

    xacro2mjcf = Node(
        package="mujoco_ros2_control",
        executable="xacro2mjcf.py",
        parameters=[{'robot_descriptions': [robot_description_string]},
                    # robot descriptions of ros robots (it is possible to load multiple robot descriptions, but ros use only one at time
                    {'input_files': [  # Paths to all files that must be included, like free joints or scene files
                        mujoco_scene_file,
                        mujoco_box_file,
                        #mujoco_table_file
                    ]},
                    {'output_file': mujoco_model_file},  # Path to the output file
                    {'mujoco_files_path': mujoco_model_path}]
        # Path to the output folder (the output file must be in this folder)
    )

    robot_state_publisher = Node(
        package="robot_state_publisher",
        executable="robot_state_publisher",
        name="robot_state_publisher",
        namespace=namespace,
        parameters=[robot_description]
    )

    ros2_control_params_file = os.path.join(
        get_package_share_directory('panda_simulation'),
        'config',
        'controllers.yaml'
    )

    mujoco = Node(
        package="mujoco_ros2_control",
        executable="mujoco_ros2_control",
        namespace=namespace,
        respawn=True,
        parameters=[
            robot_description,
            ros2_control_params_file,
            {"simulation_frequency": 1000.0},  # Hz
            {"realtime_factor": 1.0},  # 1.0 is realtime
            {"robot_model_path": mujoco_model_file},  # Path to the mujoco model file, that was generated by xacro2mjcf
            {"show_gui": True},  # Enable or disable the mujoco GUI
            {"clock_publisher_frequency": 0.0}]
        # If 0 the clock is published with sumulation frequency, otherwise it is in Hz
    )

    start_mujoco = RegisterEventHandler(
        OnExecutionComplete(
            target_action=xacro2mjcf,
            on_completion=[
                LogInfo(msg='Created mujoco xml'),
                mujoco
            ]
        )
    )

    load_joint_state_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'joint_state_broadcaster'],
        output='screen'
    )

    load_arm_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'cartesian_impedance_controller'],
        output='screen'
    )

    load_gripper_controller = ExecuteProcess(
        cmd=['ros2', 'control', 'load_controller', '--set-state', 'active',
             'gripper_controller'],
        output='screen'
    )

    register_controllers = RegisterEventHandler(
        OnProcessStart(
            target_action=mujoco,
            on_start=[
                LogInfo(msg='MuJoCo started, spawning robot'),
                load_joint_state_controller,
                load_arm_controller,
                load_gripper_controller
            ]
        )
    )

    return LaunchDescription(
        [
            start_mujoco,
            register_controllers,
            xacro2mjcf,
            robot_state_publisher
        ]
    )
