left_hip_yaw_joint:
  limit:
    lower: -0.43
    upper: 0.43
    velocity: 23
    effort: 200

left_hip_pitch_joint:
  limit:
    lower: -3.14
    upper: 2.5
    velocity: 23
    effort: 200

left_hip_roll_joint:
  limit:
    lower: -0.43
    upper: 3.14
    velocity: 23
    effort: 200

left_knee_joint:
  limit:
    lower: -0.12
    upper: 2.19
    velocity: 14
    effort: 300

left_ankle_pitch_joint:
  limit:
    lower: -0.897334
    upper: 0.523598
    velocity: 9
    effort: 60

left_ankle_roll_joint:
  limit:
    lower: -0.261799
    upper: 0.261799
    velocity: 9
    effort: 40

right_hip_yaw_joint:
  limit:
    lower: -0.43
    upper: 0.43
    velocity: 23
    effort: 200

right_hip_pitch_joint:
  limit:
    lower: -3.14
    upper: 2.5
    velocity: 23
    effort: 200

right_hip_roll_joint:
  limit:
    lower: -3.14
    upper: 0.43
    velocity: 23
    effort: 200

right_knee_joint:
  limit:
    lower: -0.12
    upper: 2.19
    velocity: 14
    effort: 300

right_ankle_pitch_joint:
  limit:
    lower: -0.897334
    upper: 0.523598
    velocity: 9
    effort: 60

right_ankle_roll_joint:
  limit:
    lower: -0.261799
    upper: 0.261799
    velocity: 9
    effort: 40

torso_joint:
  limit:
    lower: -2.35
    upper: 2.35
    velocity: 23
    effort: 200

left_shoulder_pitch_joint:
  limit:
    lower: -3.14
    upper: 1.57
    velocity: 9
    effort: 40

left_shoulder_roll_joint:
  limit:
    lower: -0.38
    upper: 3.4
    velocity: 9
    effort: 40

left_shoulder_yaw_joint:
  limit:
    lower: -2.66
    upper: 3.01
    velocity: 20
    effort: 18

left_elbow_joint:
  limit:
    lower: -0.95
    upper: 3.18
    velocity: 20
    effort: 18

left_wrist_roll_joint:
  limit:
    lower: -3.01
    upper: 2.75
    velocity: 31.4
    effort: 19

left_wrist_pitch_joint:
  limit:
    lower: -0.4625
    upper: 0.4625
    velocity: 31.4
    effort: 19

left_wrist_yaw_joint:
  limit:
    lower: -1.27
    upper: 1.27
    velocity: 31.4
    effort: 19

right_shoulder_pitch_joint:
  limit:
    lower: -3.14
    upper: 1.57
    velocity: 9
    effort: 40

right_shoulder_roll_joint:
  limit:
    lower: -3.4
    upper: 0.38
    velocity: 9
    effort: 40

right_shoulder_yaw_joint:
  limit:
    lower: -3.01
    upper: 2.66
    velocity: 20
    effort: 18

right_elbow_joint:
  limit:
    lower: -0.95
    upper: 3.18
    velocity: 20
    effort: 18

right_wrist_roll_joint:
  limit:
    lower: -2.75
    upper: 3.01
    velocity: 31.4
    effort: 19

right_wrist_pitch_joint:
  limit:
    lower: -0.4625
    upper: 0.4625
    velocity: 31.4
    effort: 19

right_wrist_yaw_joint:
  limit:
    lower: -1.27
    upper: 1.27
    velocity: 31.4
    effort: 19

L_thumb_proximal_yaw_joint:
  limit:
    lower: -0.1
    upper: 1.3
    velocity: 0.5
    effort: 1

L_thumb_proximal_pitch_joint:
  limit:
    lower: -0.1
    upper: 0.6
    velocity: 0.5
    effort: 1

L_thumb_intermediate_joint:
  limit:
    lower: 0
    upper: 0.8
    velocity: 0.5
    effort: 1

L_thumb_distal_joint:
  limit:
    lower: 0
    upper: 1.2
    velocity: 0.5
    effort: 1

L_index_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_index_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_middle_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_middle_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_ring_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_ring_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_pinky_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

L_pinky_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_thumb_proximal_yaw_joint:
  limit:
    lower: -0.1
    upper: 1.3
    velocity: 0.5
    effort: 1

R_thumb_proximal_pitch_joint:
  limit:
    lower: -0.1
    upper: 0.6
    velocity: 0.5
    effort: 1

R_thumb_intermediate_joint:
  limit:
    lower: 0
    upper: 0.8
    velocity: 0.5
    effort: 1

R_thumb_distal_joint:
  limit:
    lower: 0
    upper: 1.2
    velocity: 0.5
    effort: 1

R_index_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_index_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_middle_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_middle_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_ring_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_ring_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_pinky_proximal_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1

R_pinky_intermediate_joint:
  limit:
    lower: 0
    upper: 1.7
    velocity: 0.5
    effort: 1
    